name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      continue-on-error: true
      run: |
        pylint --output-format=text $(git ls-files '*.py') > pylint_report.txt || true
    - name: Display PyLint results
      run: |
        echo "PyLint Results:"
        cat pylint_report.txt
    - name: Run tests with pytest
      run: |
        echo "pytest"
        pytest
